name: CI

on:
  push:
  pull_request:

env:
  HONEYCOMBIO_DATASET: kvrhdn-terraform-provider-honeycombio

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.HONEYCOMBIO_APIKEY }}
          dataset: ${{ env.HONEYCOMBIO_DATASET }}
          job-status: ${{ job.status }}

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - uses: actions/checkout@v2

      - name: Build
        run: go build -v .

      - name: Test
        env:
          HONEYCOMBIO_APIKEY: ${{ secrets.HONEYCOMBIO_APIKEY }}
          TF_ACC: 1
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  fmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.HONEYCOMBIO_APIKEY }}
          dataset: ${{ env.HONEYCOMBIO_DATASET }}
          job-status: ${{ job.status }}

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - uses: actions/checkout@v2

      - name: Check formatting
        run: |
          # install goimports from another directory to not touch go.mod
          pushd ../
          go get golang.org/x/tools/cmd/goimports
          popd

          goimports -l -w .
          go mod tidy

          if ! git diff --quiet; then
            exit 1
          fi
