name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    name: Release (GoReleaser)
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.HONEYCOMBIO_APIKEY }}
          dataset: ${{ env.HONEYCOMBIO_DATASET }}
          job-status: ${{ job.status }}

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        id: import_gpg

      - name: Get version from tag
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}
        id: version

      - uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ steps.version.outputs.tag_version }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}          
